### ISSUE TITLE
Bug: duplicate events being saved

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#254] opened 2023-04-19 18:21 UTC
While I was debugging in RelayService.parseEvent I noticed that we were saving multiple events with the same ID into our database. This is a bug and we should fix it because it will appear as other very-hard-to-debug bugs in the future.

**Comment by setch-l** [comment] 2023-12-12 20:15
This is duplicate of #703

**Closed by setch-l** 2023-12-12 20:15 UTC
Labels: tech
