### ISSUE TITLE
[bug] Notfications tab UI locks and then app sometimes crashes

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1009] opened 2024-04-09 15:06 UTC
Steps to reproduce

1. Open the nos app
2. Navigate to the notifications tab
Issue: UI locks and the user cannot take any action
Sometimes the app crashes.

**Comment by joshuatbrown** [comment] 2024-04-24 19:56
This is a duplicate of #1077 and/or #970.

**Closed by joshuatbrown** 2024-04-24 19:56 UTC
Labels: bug
