### ISSUE TITLE
Buttons inside sheets change to red after swiping through, but not tapping to

### ISSUE THREAD

**Issue by martindsq** [planetary-social/nos#1064] opened 2024-04-19 14:44 UTC
**Describe the bug**

**To Reproduce**
1. Go to Profile
2. Tap on the three dots
3. Swipe through the options without tapping them, either in the simulator or an actual device
4. See all options turned permanently to red

**Expected behavior**
The buttons should return to their former colors.

**Screenshots or Video**
https://github.com/planetary-social/nos/assets/1703242/c5a51d9d-4435-4c9c-b038-c953d5cb51d9

**Technical info (please complete the following information):**
 - OS: iOS
 - App Version: 0.1.11
 - Environment: All of them

**Additional context**
We initially thought it was due to a destructive action we had in one sheet, but it happens in all of them. I don't think it is a destructive red, but it seems to me that the "active" or "selected" state of the buttons are set somewhere or are buggy in swiftui. We could create a new project and find out. Also, the dark mode could be interacting with that.

**Comment by bryanmontz** [comment] 2024-08-09 13:04
This issue reproduces on iOS 17.5 and 18.0 simulators.

I tried a small test project and the issue did NOT reproduce there.

**Comment by bryanmontz** [comment] 2024-08-09 13:20
Here is a relevant page from the Apple Developer Forums:  
https://forums.developer.apple.com/forums/thread/673147

**Comment by joshuatbrown** [comment] 2024-08-16 18:19
@setch-l Reopening and putting into QA since this will be in the 0.1.25 build.

**Closed** 2024-09-17 19:08 UTC
Labels: bug
