### ISSUE TITLE
Tapping on reply notifications do not take me to right place in the thread

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#874] opened 2024-02-10 04:41 UTC
When I’m getting notifications from active threads it is very hard to find the reply because tapping on a card in the notifications list does not take you to that specific note. It should take you right to that post!

Uploading RPReplay_Final1707539764.mp4…

**Comment by setch-l** [comment] 2024-02-12 15:20
This is dupe of this ticket: https://github.com/planetary-social/nos/issues/668 -

**Comment by rabble** [comment] 2024-02-12 18:47
This is a different issue than #668. This one is the tap area on the notification note card is wrong. The #668 bug is that once a thread is opened the scroll position is not right.

**Closed** 2024-02-12 18:49 UTC
