### ISSUE TITLE
[Bug] We don't support this nprofile format in the feed view

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1234] opened 2024-06-12 23:00 UTC
Steps to reproduce
1. Visit this note in Nostr: note1ar8gnwj6ugxyq6w9aqur74s2sn4dttk6zx0d25p34fsg476kqrksmkqqnr
Issue: the nprofile link is rendered as a string instead of what it should be. 
Expected: I think this is a mention and it should render as @ the person as a link along with a link to the note. 

![Image](https://github.com/planetary-social/nos/assets/6765558/5d55d1ab-f718-44ce-b47f-42cba72097db)

**Comment by rabble** [comment] 2024-06-13 06:06
This is a subset and dupe of #285

**Comment by joshuatbrown** [comment] 2024-07-10 17:52
Other notes to test:

- note1alva8prc6ae0r973erz25fg5pcdfs8pq5gnfhzefvylf6zzv2vvsys344q
- note1w6u6stxxvr78lat6d9sknsac0jnpj7ylpm6sfjxgmg7euulpczyq5asrw2

**Closed** 2024-07-31 15:08 UTC
Labels: bug
