### ISSUE TITLE
[cleanstr] Don't delete reports from the database

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#651] opened 2023-11-17 15:31 UTC
The database cleanup script currently deletes reports alongside other old events. We should keep them for longer, especially the ones for authors.

**Comment by setch-l** [comment] 2023-12-18 21:29
This is a duplicate of https://github.com/planetary-social/nos/issues/728 - Will close.

**Closed by setch-l** 2023-12-18 21:29 UTC
Labels: bug
