### ISSUE TITLE
[Bug] naddr events do not link and are not supported in Nos

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1232] opened 2024-06-12 16:31 UTC
One of our Creators - Onigirl uses a client that creates naddr events. As a result most of the links in her notes are broken when someone views them in Nos. 

Steps to Reproduce:
1. Open this note: note1zfrg4pehc3ap9s82jgxa44zsqn5kra8qhdc6gq5h3nhac4d377tszen8mq
2. Try clicking on a Tap link 
Issue: Nothing happens when you click and when you scroll down you can see the formatting is this weird naddr format. 
Expected: Assuming this is not an audio post that we do not support, we should render this event. (My guess it is some sort of long form post). 

![Image](https://github.com/planetary-social/nos/assets/6765558/46c96798-b5b8-482e-bd7f-626887fd2cbe)

**Comment by rabble** [comment] 2024-06-13 06:05
This is a subset of and dupe of #285

**Comment by setch-l** [comment] 2024-06-13 16:43
Hi @rabble - I think you bring up a good point in terms of these tickets being a subset of #285 . #285 is at the epic or even initiative level. It asks for support in both the view of these n things as well as in search. It's at the epic or initiative level bc it is not likely that we would assign Matt to take care of the view things, whereas we would probably assign him to take care of the search work. In addition, there's a lot of work to simply support the n things in views as well as a lot of work and edge cases to support n things in search. 

In other tools - different types of "issues" exist - there are epics and sometimes even initiatives. Github lacks that functionality (and Jira's implementation of epics is mediocre at best). It might be helpful to think of the tickets I put in as tasks that can be assigned and taken on by specific developers. 

They may not be bugs and instead are product debt, but I think it's helpful for the team to have direct examples so they don't spend time trying to find examples or create examples and can instead focus on building out the functionality. 

I've noted the need to support all these n things in search as well and when we get to that, I'll make sure we have tickets for that work when we get to search.

**Closed** 2024-07-31 15:07 UTC
Labels: bug
