### ISSUE TITLE
Viewing event / note which isn't loaded doesn't work. You see the replies but not the root

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#704] opened 2023-12-05 19:49 UTC
When clicking on a link to a note in build 98 it doesn't ever load that note. It just loads the replies. This is a reversion as this was fixed before.

**Comment by mplorentz** [comment] 2023-12-07 22:33
This is probably a dupe of #697.

**Comment by mplorentz** [comment] 2024-01-05 19:31
Also dupe of #703

**Closed by mplorentz** 2024-01-05 19:31 UTC
