### ISSUE TITLE
[Relays] Remove snort.social from the list of auto-assigned relays

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1427] opened 2024-08-27 17:58 UTC
relay.snort.social has gone private. Let's remove the snort relay from our auto-populated list for new users until the new countries relay is ready.

**Comment by joshuatbrown** [comment] 2024-08-29 15:26
@mplorentz I think you've done this already in #1439, and this ticket is a duplicate of #1377.

**Comment by mplorentz** [comment] 2024-08-30 19:54
Good call. I think they are slightly different because this one is just about removing snort but the other wants to add a countries relay. I'll send this one to UAT and the other one back to the backlog.

**Closed** 2024-09-25 19:11 UTC
