### ISSUE TITLE
Can't click on links from note card view

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#284] opened 2023-04-29 05:02 UTC
![D6C27AC7-EE37-4641-8B07-1A1B385DA6C7_1_201_a](https://user-images.githubusercontent.com/76/235284477-15c0583d-c164-4077-897e-584ecd95e51e.jpeg)

On the note card view when you try and tap on a web link it shows that there's been a tap but doesn't open the link.

**Comment by mplorentz** [comment] 2023-05-09 19:48
@rabble also reports that nothing above the bottom row of buttons on the note is tappable. Let's sit down and debug on his device.

**Comment by martindsq** [comment] 2023-05-16 18:56
I can't either, I'll assign this to me

**Comment by mplorentz** [comment] 2023-05-23 19:45
Confirmed by @rabble that he can't reproduce this anymore.

**Closed by mplorentz** 2023-05-23 19:45 UTC
Labels: bug, good first issue, help wanted, regression
