### ISSUE TITLE
[Bug] Photo upload is not working

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1204] opened 2024-05-30 17:50 UTC
Steps to reproduce:
1. Open the app on the phone
2. Click post
3. try to upload a photo without entering any text. 
Issue: Receive an error message that photo upload doesn't work

Seen on build 250 and 304 on staging

**Comment by joshuatbrown** [comment] 2024-05-30 17:59
I can reproduce this with a variety of devices (Mac, iOS Simulator, iPhone 13 Pro) and accounts (my personal one, plus a couple test accounts). The strange thing is: I can also reproduce this on old builds of the app, like Nos Staging 0.1.11 (245) and Nos 0.1.14 (246).

**Comment by joshuatbrown** [comment] 2024-05-30 18:57
OK, we discovered that nostr.build just [shut down their old API](https://github.com/nostrbuild/nostr.build/pull/69), which is what we're using in Nos. We'll have to use their new API, which requires direct communication with them since it's not publicly available or documented. Well, we might be able to get some details from [the nostr.build code](https://github.com/nostrbuild/nostr.build/blob/main/api/v2/routes_upload.php), but we definitely still want to check and make sure we get it all set up the way they want.

**Comment by joshuatbrown** [comment] 2024-05-31 14:41
Our quick fix has been merged; I'd love to prioritize #1208 so we can hopefully avoid this type of issue in the future.

**Closed** 2024-06-04 15:52 UTC
Labels: bug
