### ISSUE TITLE
[In Discussion] Replace Reply count w/ WOT in discussion

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1246] opened 2024-06-18 17:05 UTC
Given that I am a user of Nos 
When I scroll my feed
Then I want to see which of the people I follow are in a discussion on each note. 
(NOTE: These changes only apply to the feed view. The thread view remains the same.) 

AC 
- Show up to 4 people the person follows icons in discussion on any given Note 
- If there are replies detected but not in WOT, show join discussion w/ an orange conversation box
- If there are no detected replies, show a white conversation box

Design (note you should use styles in the app for this work, the design below is for reference only) 
https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=6884-618&t=JhWjDxsaCzzpqXHA-1

**Comment by setch-l** [comment] 2024-07-16 15:26
@martindsq - Why didn’t you change the conversation box to orange as the ticket indicates?

**Comment by mplorentz** [comment] 2024-07-17 13:27
I'm seeing a lot of "too many concurrent REQs" errors from relays after this has been merged. I think this means our limit for the max number of subscriptions is too high. I'll try lowering it and see if that helps.

**Comment by mplorentz** [comment] 2024-07-22 17:37
I found another issue caused by the PR for this. I described and fixed it [here](https://github.com/planetary-social/nos/pull/1323), but basically paging was broken on profiles and in general you couldn't scroll back more than a few days.

**Closed** 2024-07-31 15:08 UTC
